# Путь к файлу: models/marts/schema.yml

version: 2

models:
  - name: shipping_dim
    columns:
      - name: ship_id
        tests:
          - unique
          - not_null

  - name: customer_dim
    columns:
      - name: cust_id
        tests:
          - unique
          - not_null

  - name: geo_dim
    columns:
      - name: geo_id
        tests:
          - unique
          - not_null

  - name: product_dim
    columns:
      - name: prod_id
        tests:
          - unique
          - not_null

  - name: sales_fact
    columns:
      - name: cust_id
        tests:
          - relationships:
              arguments:  
                to: ref('customer_dim')
                field: cust_id
  
  - name: mart_order_processing_time
    columns:
      - name: sub_category
        tests:
          - not_null
          - unique
      - name: avg_processing_days
        tests:
        - not_null